# ground_truth/body_part_patterns.py
# -------------------------------------
# Exact translation of the SQL body part CASE block.
# ORDER MATTERS — first match wins, just like SQL CASE WHEN.
# Multi-body parts must stay above single body parts.
# SQL matches against UPPER(c.study_name) — pattern_review.py uppercases before matching
# AND uses re.IGNORECASE for parity with MySQL's case-insensitive collation.

BODY_PART_PATTERNS = [

    # ── Multi-body parts (must come first) ────────────────────────────────────
    (r'CHEST.*(ABDOMEN|ABD).*(PELVIS|PELV)|CHEST/ABD/PELVIS|CHEST ABDOMEN PELVIS|CHEST\+ABD.*PELVIS',  'Chest, Abdomen, Pelvis'),
    (r'CHEST.*(ABDOMEN|ABD)|CHEST\+ABD',                                                               'Chest, Abdomen'),
    (r'CHEST.*THORAX|CHEST/THORAX',                                                                    'Chest, Thorax'),
    (r'(ABDOMEN|ABD).*(PELVIS|PELV)|(PELVIS|PELV).*(ABDOMEN|ABD)',                                    'Abdomen, Pelvis'),
    (r'HEAD.*NECK|NECK.*HEAD|NECK/HEAD',                                                               'Head, Neck'),
    (r'ORB.*FAC.*NCK|ORBIT.*FACE.*NECK|ORBIT/FACE/NK',                                                'Orbit, Face, Neck'),
    (r'ORBIT.*SELLA|ORBIT\+SELLA|ORBIT SELLA POSS|ORBIT\+SELLA\+PF',                                 'Orbit, Sella'),
    (r'CERVICOTHORACOLUMBAR|CERVICO.*THORACO.*LUMBAR',                                                 'Thoracic Spine, Lumbar Spine'),
    (r'THORACO.?LUMBAR|THORACOLUMBAR|THOR.*LUM[B]|THOR\+LU[MB]',                                      'Thoracic Spine, Lumbar Spine'),
    (r'LUMBOSACRAL PLEXUS',                                                                            'Lumbar Spine, Sacrum'),
    (r'LUMBO.?SACRAL|LUMB.?SACR|LUMBO SACRAL|LUMBOSACRAL',                                           'Lumbar Spine, Sacrum'),
    (r'SACRUM.*(AND|\+|/).?COCCYX|SACRUM COCCYX|SACRUM/COCCYX',                                       'Sacrum, Coccyx'),
    (r'FACIAL.*SINUS|SINUS.*FACIAL|FACIAL/SINUS|MAX.*FAC.*SIN|MAXILLOFACIAL|MAXIOFACIAL|MAXFACIAL|MAXILLA|SINUS FACIAL|MAX/FAC/SIN|MAXFACIAL BONES', 'Facial Bones, Sinuses'),
    (r'TIB.?FIB|TIBIA.?FIBUL|TIBIA AND FIBULA|TIBIA/FIBULA|TIB & FIB|TIB\+FIBULA|TIBIA\+FIBULA|TM JOINTS|TIB\s*\\T\\\s*FIB|TIB\s+T\s+FIB', 'Tibia, Fibula'),
    (r'FOREARM.*RADIUS|FOREARM.*ULNA|RADIUS.*ULNA|FOREARM/RADIUS',                                    'Forearm, Radius, Ulna'),
    (r'CAROTID.*NECK|CAROTID/NECK|VASC CAROTID|CAROTIDS',                                             'Carotid, Neck'),
    (r'THYROID.*NECK|THY.*NECK|THYROID/NECK',                                                         'Thyroid, Neck'),
    (r'LIVER.*GALLBLADDER.*PANCREAS|LIVER GALLBLADDER PANCREAS',                                       'Liver, Gallbladder, Pancreas'),
    (r'ILIUM.*STERNUM.*RIB|ILIUM STERNUM RIB',                                                        'Ilium, Sternum, Rib'),
    (r'AC JOINTS|ACROMIOCLAVICULAR JOINTS|STERNOCLAVIC|STERNOCLAVICULAR',                              'Acromioclavicular Joints'),
    (r'\bTMJ\b|TEMPOROMANDIBULAR|TEMPOROMANDIBULAR JOINT|TMJ BILATERAL',                               'Temporomandibular Joint'),
    (r'VASC EXT LOWR|VASC EXTREMITY LOWER|LOWER EXTREMITY VENOUS|LOWER EXT VENOUS|LOWER EXTREMITY ARTERIES|LOWER EXT ARTERIAL|ARTERIAL LOW.*EXT|ARTERIAL LOWER EXT|ARTERIAL LOWER EXTREMITY|LOWER EXTREMITY ARTERI', 'Lower Extremity (Vascular)'),
    (r'UPPER EXTREMITY VENOUS|UPPER EXT.*ARTERIAL|ARTERIAL UPPER EXT|ARTERIAL UPPER EXTREMITY|UPPER EXTREMITY ARTERIAL|LT UPPER VENOUS|UPPER OR LOWER EXT ARTERIAL', 'Upper Extremity (Vascular)'),
    (r'VASC TRANSCRANIAL|TRANS CRANIAL|TRANSCRANIAL|VASC JUGULAR|JUGULAR.*SUBCLAVIAN',                'Transcranial (Vascular)'),
    (r'CEREBRAL ARTERIES|EXTRACRANIAL ARTERIES',                                                       'Cerebral Arteries'),
    (r'\bLOWER EXTREMIT|\bLOWER EXT\b|\bLOWER EXTR\b|\bLWR EXT\b|\bLE\b|\bLOW EXT\b|\bLEFT LOWER EXTREMITY\b|\bRIGHT LOWER EXTREMITY\b|LOWER EXT.*NOT.*JNT|LOWER EXT.*NON|LWR EXT NOT JT|LOWER LEG|LOWER BACK|EXTREMITY LOWER|EXTREMITY.*LOWER', 'Lower Extremity'),
    (r'\bUPPER EXTREMIT|\bUPPER EXT\b|\bUPR.*EXT\b|\bUPR/LXTR\b|UP EXT JT|LEFT EXTREMITY.*UPPER|UPPER EXT.*JOINT|UPPER EXT NON JOINT|UPPER EXTREMITY.*MUSCULO|EXTREMITY UPPER|EXTREMITY.*UPPER|LEFT EXTREMITY JOINT UPPER|RIGHT EXTREMITY JOINT LOWER', 'Upper Extremity'),
    (r'BRACHIAL PLEXUS|RIGHT BRACHIAL PLEXUS|\bBRACHPLEX\b',                                          'Brachial Plexus'),
    (r'SPINAL CANAL|SPINAL CORD|THORACIC SPINAL CORD|SPINAL CORD DORSAL',                             'Spinal Canal'),
    (r'SACROILIAC|SACROILIAC JOINT|SACROILIAC JNTS|SI JOINT',                                         'Sacroiliac Joint'),

    # ── Single body parts ──────────────────────────────────────────────────────
    (r'\bABDOMEN\b|\bABD\b|\bABDOMINAL\b',                                                            'Abdomen'),
    (r'\bANKLE\b|\bANK\b',                                                                             'Ankle'),
    (r'\bAORTA\b|\bTHORACIC AORTA\b',                                                                  'Aorta'),
    (r'\bARTERY\b|\bARTERIAL\b',                                                                       'Arterial'),
    (r'AUDITORY CANAL',                                                                                 'Auditory Canal'),
    (r'AXIAL SKELETON',                                                                                 'Axial Skeleton'),
    (r'\bBONE\b',                                                                                      'Bone'),
    (r'\bBRAIN\s*STEM\b|\bBRN\s*STEM\b|\bBRAINSTEM\b',                                                'Brain Stem'),
    (r'\bBRAIN\b|\bBRIAN\b|\bBRIN\b',                                                                  'Brain'),
    (r'\bIAC\b|\bIACS\b|INTERNAL AUDITORY|AUDITORY MEATUS|AUDITORY CANAL MRI',                        'Internal Auditory Canal'),
    (r'\bTRIGEMINAL\b|\b5TH.*NERVE\b|\bCN\s*V\b|\bCRANIAL NERVE\s*5\b',                             'Trigeminal Nerve'),
    (r'\b7TH.*NERVE\b|\bCN\s*VII\b|\bCRANIAL NERVE\s*7\b|\bFACIAL NERVE\b',                         'Facial Nerve'),
    (r'\b8TH.*NERVE\b|\bCN\s*VIII\b|\bCRANIAL NERVE\s*8\b|\bACOUSTIC NEUROMA\b|\bVESTIBULOCOCHLEAR\b', 'Acoustic Nerve'),
    (r'\bCARDIAC\b|\bCARDIOVASC\b',                                                                   'Heart'),
    (r'\bSACRAL PLEXUS\b',                                                                             'Sacrum'),
    (r'MUSCLE.*\bUE\b|MUSCLE.*UPPER|MUSCLE.*\bUPR\b',                                                 'Upper Extremity'),
    (r'MUSCLE.*\bLE\b|MUSCLE.*LOWER|MUSCLE.*\bLWR\b',                                                 'Lower Extremity'),
    (r'VISUAL EVOKED|EVOKED.*VISUAL|EVOKED.*POTENTIAL.*VIS',                                           'Eye / Orbit'),
    (r'\bL-SPINE\b|\bL SPINE\b|\bLS-SPINE\b|\bL-S SPINE\b|\bLS SPINE\b',                             'Lumbar Spine'),
    (r'\bT-SPINE\b|\bT SPINE\b|\bTHORACIC SPINE\b',                                                  'Thoracic Spine'),
    (r'\bBREAST\b|\bBREASTS\b',                                                                        'Breast'),
    (r'\bCALF\b',                                                                                      'Calf'),
    (r'\bCAROTID\b|\bCAROTIDS\b',                                                                      'Carotid'),
    (r'\bCERVICAL SPINE\b|\bSPINE CERVICAL\b|\bC-SPINE\b',                                            'Cervical Spine'),
    (r'\bCERVICAL\b',                                                                                  'Cervical'),
    (r'\bCHEST\b|\bPA CHEST\b|\bCHEST PA\b|\bTHORAX\b|\bRIBS\b|\bPNEUMOTHORAX\b|\bTHORACENTESIS\b', 'Chest'),
    (r'\bCLAVICLE\b',                                                                                  'Clavicle'),
    (r'\bCOCCYX\b',                                                                                    'Coccyx'),
    (r'\bCOLON\b|\bLARGE INTESTINE\b',                                                                 'Colon'),
    (r'CRANIAL NERVE',                                                                                  'Cranial Nerve'),
    (r'\bEAR\b',                                                                                       'Ear'),
    (r'\bELBOW\b|\bELB\b',                                                                             'Elbow'),
    (r'\bESOPHAGUS\b|\bTRANSESOPHAGEAL\b',                                                            'Esophagus'),
    (r'\bEXTRACRANIAL\b|\bEXTRACRAN\b',                                                               'Extracranial'),
    (r'\bEYE\b|\bORBIT\b|\bORBITS\b|\bORB\b|OPTIC NERVE',                                             'Eye / Orbit'),
    (r'\bFACE\b|\bFACIAL\b|\bFACIAL BONES\b',                                                         'Face'),
    (r'\bFEMUR\b|\bFEM\b|\bLATERAL FEMORAL\b',                                                        'Femur'),
    (r'\bFINGERS\b|\bFINGER\b',                                                                        'Fingers'),
    (r'\bFOOT\b|\bFEET\b|\bFT\b|\bHEEL\b',                                                           'Foot'),
    (r'\bFOREARM\b|\bFORE\b',                                                                          'Forearm'),
    (r'\bGALLBLADDER\b',                                                                               'Gallbladder'),
    (r'\bGI\b|\bUGI\b|\bGASTRIC\b|\bGASTROINTESTINAL\b|\bSMALL INTESTINE\b|\bSTOMACH\b|\bBOWEL\b',  'Gastric / GI'),
    (r'GREATER OCCIPITAL|OCCIPITAL',                                                                    'Occipital'),
    (r'\bGROIN\b|\bILIOINGUINAL\b',                                                                    'Groin'),
    (r'\bHAND\b|\bHANDS\b',                                                                            'Hand'),
    (r'\bHEAD\b|\bORBITS\b',                                                                           'Head'),
    (r'\bHEART\b|\bTRANSTHORACIC\b',                                                                  'Heart'),
    (r'\bHIP\b|\bHIPS\b',                                                                              'Hip'),
    (r'\bHUMERUS\b|\bHUM\b|\bUPPER ARM\b',                                                            'Humerus / Upper Arm'),
    (r'\bINTRACRANIAL\b|\bINTRACRAN\b',                                                               'Intracranial'),
    (r'\bKIDNEY\b|\bKIDNEYS\b|\bRENAL\b',                                                             'Kidney'),
    (r'\bKNEE\b|\bKNEES\b|\bKN\b',                                                                    'Knee'),
    (r'\bLEG\b|\bLOWER LEG\b',                                                                         'Leg'),
    (r'\bLIVER\b',                                                                                     'Liver'),
    (r'LUMBAR PLEXUS|LUMPLEX',                                                                          'Lumbar Plexus'),
    (r'\bLUMBAR SPINE\b|\bSPINE LUMBAR\b|\bLUMBOSACRAL\b|\bLUMOSACRAL\b',                           'Lumbar Spine'),
    (r'\bLUMBAR\b',                                                                                    'Lumbar'),
    (r'\bLUNG\b',                                                                                      'Lung'),
    (r'LYMPH NODE',                                                                                     'Lymph Node'),
    (r'\bMANDIBLE\b',                                                                                  'Mandible'),
    (r'\bMASTOIDS\b|\bMASTOID\b',                                                                      'Mastoids'),
    (r'\bNECK\b|\bNECK SOFT TISSUE\b|\bTHROAT\b',                                                    'Neck'),
    (r'\bPANCREAS\b',                                                                                  'Pancreas'),
    (r'\bPARATHYROID\b',                                                                               'Parathyroid'),
    (r'\bPELVIS\b|\bPELVIC\b',                                                                        'Pelvis'),
    (r'\bPITUITARY\b|\bPITUITARY GLAND\b|\bSELLA TURCICA\b|\bSELLA\b',                               'Pituitary'),
    (r'\bPROSTATE\b|\bRECTAL\b',                                                                      'Prostate / Rectal'),
    (r'\bRETROPERITONEUM\b',                                                                           'Retroperitoneum'),
    (r'\bSACRUM\b',                                                                                    'Sacrum'),
    (r'\bSCAPULA\b|\bSCAP\b',                                                                          'Scapula'),
    (r'\bSCOLIOSIS\b',                                                                                 'Scoliosis'),
    (r'\bSCROTAL\b|\bSCROTUM\b|\bTESTICULAR\b|\bTESTICLE\b|\bTESTES\b',                             'Scrotal / Testicular'),
    (r'\bSHOULDER\b|\bSH\b|UPPER EXT JOINT SHOULDER|\bSHOULDERS\b',                                  'Shoulder'),
    (r'\bSINUS\b|\bSINUSES\b|\bNASAL\b|\bSINUS/NASAL\b',                                             'Sinuses'),
    (r'\bSKULL\b',                                                                                     'Skull'),
    (r'SPINAL CORD DORSAL',                                                                             'Spinal Cord'),
    (r'\bSPINE\b|\bSCPINE\b',                                                                          'Spine'),
    (r'\bSPLEEN\b',                                                                                    'Spleen'),
    (r'\bSTERNUM\b',                                                                                   'Sternum'),
    (r'\bTEETH\b',                                                                                     'Teeth'),
    (r'\bTHUMB\b',                                                                                     'Thumb'),
    (r'TEMPORAL BONE',                                                                                  'Temporal Bone'),
    (r'\bTHIGH\b|\bTHIGHS\b',                                                                         'Thigh'),
    (r'\bTHORACIC\b',                                                                                  'Thoracic'),
    (r'\bTHYROID\b',                                                                                   'Thyroid'),
    (r'\bTOES\b|\bTOE\b',                                                                              'Toes'),
    (r'\bTORSO\b|\bPE TORSO\b',                                                                       'Torso'),
    (r'TRANSVAGINAL|TRANS-VAGINAL|TRANS VAGINAL',                                                      'Transvaginal'),
    (r'\bUTERUS\b',                                                                                    'Uterus'),
    (r'VAGUS NERVE',                                                                                    'Vagus Nerve'),
    (r'\bVEINS\b|\bVENOUS\b',                                                                          'Veins'),
    (r'WHOLE BODY',                                                                                     'Whole Body'),
    (r'\bWRIST\b|\bWRISTS\b|\bWR\b',                                                                  'Wrist'),

    # ELSE 'NS' → returned as None by classify(), written as null in CSV
]
